import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen">
      <div className="flex flex-col md:flex-row">
        {/* Sidebar on top for small devices, on the left for large devices */}
        <div className="w-full md:w-[20%]">
          <Sidebar />
        </div>

        {/* Main content */}
        <div className="w-full md:w-[80%] bg-base-200 rounded-box p-2">
          {children}
        </div>
      </div>
    </div>
  );
}
